name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - run: ls -l 
      - run: sudo apt-get update && sudo apt-get install -y cowsay
      - run: cat README.md | cowsay